stages:
  - build
  - deploy

build:
  stage: build
  script:
    - dotnet build ./src/MagicOnion/ -c Release #-p:VersionPrefix=${{ env.GIT_TAG }}
    - dotnet build ./src/MagicOnion.Abstractions/ -c Release #-p:VersionPrefix=${{ env.GIT_TAG }}
    - dotnet build ./src/MagicOnion.Shared/ -c Release #-p:VersionPrefix=${{ env.GIT_TAG }}
    - dotnet build ./src/MagicOnion.Client/ -c Release #-p:VersionPrefix=${{ env.GIT_TAG }}
    - dotnet build ./src/MagicOnion.Server/ -c Release #-p:VersionPrefix=${{ env.GIT_TAG }}
    - dotnet build ./src/MagicOnion.Server.HttpGateway/ -c Release #-p:VersionPrefix=${{ env.GIT_TAG }}
    - dotnet build ./src/MagicOnion.Server.Redis/ -c Release #-p:VersionPrefix=${{ env.GIT_TAG }}
    - dotnet build ./src/MagicOnion.Server.Authentication/ -c Release #-p:VersionPrefix=${{ env.GIT_TAG }}
    - dotnet build ./src/MagicOnion.MSBuild.Tasks/ -c Release #-p:VersionPrefix=${{ env.GIT_TAG }}
    - dotnet build ./src/MagicOnion.Generator/ -c Release #-p:VersionPrefix=${{ env.GIT_TAG }}


deploy:
  stage: deploy
  script:
    #
    - dotnet pack ./src/MagicOnion/MagicOnion.csproj -c Release --no-build -p:VersionPrefix=${{ env.GIT_TAG }} -o ./publish
    - dotnet pack ./src/MagicOnion.Abstractions/MagicOnion.Abstractions.csproj -c Release --no-build -p:VersionPrefix=${{ env.GIT_TAG }} -o ./publish
    - dotnet pack ./src/MagicOnion.Shared/MagicOnion.Shared.csproj -c Release --no-build -p:VersionPrefix=${{ env.GIT_TAG }} -o ./publish
    - dotnet pack ./src/MagicOnion.Client/MagicOnion.Client.csproj -c Release --no-build -p:VersionPrefix=${{ env.GIT_TAG }} -o ./publish
    - dotnet pack ./src/MagicOnion.Server/MagicOnion.Server.csproj -c Release --no-build -p:VersionPrefix=${{ env.GIT_TAG }} -o ./publish
    - dotnet pack ./src/MagicOnion.Server.HttpGateway/MagicOnion.Server.HttpGateway.csproj -c Release --no-build -p:VersionPrefix=${{ env.GIT_TAG }} -o ./publish
    - dotnet pack ./src/MagicOnion.Server.Redis/MagicOnion.Server.Redis.csproj -c Release --no-build -p:VersionPrefix=${{ env.GIT_TAG }} -o ./publish
    - dotnet pack ./src/MagicOnion.Server.Authentication/MagicOnion.Server.Authentication.csproj -c Release --no-build -p:VersionPrefix=${{ env.GIT_TAG }} -o ./publish
    - dotnet pack ./src/MagicOnion.MSBuild.Tasks/MagicOnion.MSBuild.Tasks.csproj -c Release --no-build -p:VersionPrefix=${{ env.GIT_TAG }} -o ./publish
    - dotnet pack ./src/MagicOnion.Generator/MagicOnion.Generator.csproj -c Release --no-build -p:VersionPrefix=${{ env.GIT_TAG }} -o ./publish

    #- run: dotnet pack ./src/MagicOnion.Server.OpenTelemetry/MagicOnion.Server.OpenTelemetry.csproj -c Release --no-build -p:VersionPrefix=${{ env.GIT_TAG }} -o ./publish
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "./publish/*.nupkg" --source gitlab
  only:
    - master
